version: '3'
services:
  liku_mongodb:
    container_name: liku_mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - liku_mongodb_volume:/data/db
    networks:
      - liku_network

networks:
    liku_network:
      driver: bridge

volumes:
  liku_mongodb_volume:
